travis:
  secure:
    BINSTAR_TOKEN: UmmomiqBW9rxQAqOSOyoDUEcXDBerAdHItIDmIRviGGZ7F0e21ZAmsyijrn/e5s+N5qJcuZ05m7G/L+EpVCeYZrVGbVWrh0Rbk7E42fJQg6TgcgpjNKCP9Hw2N+WmGTny2+F9a8vqCiam3AH2OlV7ngPxmH9OaGQqMNM+1ebAsz62O70X0Jw4gJ1lB3CxwsfCurY3wCtgnP0AMTH0sCIR0mhMosQXYtGba+yGaS9QcwLIHsMfs6hTTC7DZaeZSBrd0pKbsKJEIgUd5oWsJgEu3fCav6cwPEzqdmP/DD+RRQHuFu/s7/LsIOEE3SVzWIhYcQ8uaYaXtPqOURhoB/6KDxk3kFmxveb2kuxhUi3D3v/cc5jvs90MieQXBIpDSe1sjTlqKNnrLze/p6dibvfqwLcd87/JIiG5r2bnih+0k4sJhfUWm1DltxGSh3u99kpZHgv+HD0GL4dXd4EYQyk23uInMihZsurCxqTavXdfruqCPOYTsMrPneB1XwT598+SPesGCBh6kDF/hYfr77QCe4pU68iwG7nP5NVFMF9yihxLzxAdO6iXtGjeIQwrYCT7vt1BXb4l4fukDLVoqS9LmvUgkluegjKp57yI7/OJwg94bfaxMhOCbBkzXi+KsMIUfXNNJAPlvZsdf5Ok/kjPbv7+KN3WTQpRQ8+lhJwJ7M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
